### ISSUE TITLE
conduit replica

### ISSUE THREAD

**Issue by michaelt** [chemist/pipes-bzip#2]
I made a little replica of bzlib conduit that seems to work. https://github.com/michaelt/pipes-bzlib There are several things to fret about, but the main point is that the implementation differs only on three or four lines. The first thing is that instead of a pipe/conduit, we just use a function, for compress and decompress. (This has to do with the inspection of the end, which is a basic difference between the libraries) This means that we use 

```
 e <- lift $ next p
 case e of
   ...
```

instead of `await`.  And so we recursively pass along the 'rest of the stream' when looping.

The thing that bugs me is that the compress/decompress functions use `ResourceT` rather than `Pipes.Safe`. I don't know all the ins and outs of this. In any case the following works fine

```
import           Pipes
import qualified Pipes.ByteString as PB
import qualified Pipes.BZlib as PBZ
import qualified System.IO as IO
import qualified Data.ByteString as B
import Control.Monad.Trans.Resource

main = runResourceT $ runEffect $ 
  PBZ.bunzip2 (PB.fromHandle IO.stdin) >-> PB.toHandle IO.stdout 
```

**Comment by michaelt** [comment]
Actually, if we could get snoyman to expose the internal module in `bzip-conduit` rather than marking it `other modules:` https://github.com/snoyberg/bzlib-conduit/blob/master/bzlib-conduit.cabal#L24 , then this works fine https://gist.github.com/michaelt/97d4949d8881a66d87ca

**Comment by chemist** [comment]
I rewrite library, can you check result?
